# Ejercicios de errores y excepciones

lista = [1,2,3,4]

print(lista[5])

# diccionario = {'nombre': 'Leo', 'edad': 31}

# print(diccionario['apellido'])

resultado = 10 / 0
print(resultado)


#def sumar(a, b):
    #return a + b
#resultado = sumar('chau', 7)


# Con except y finally

#try:
   #resultado = 20 / 'leo'
   #print(resultado)
#except TypeError:
   #print(f'Ha ocurrido un error.')


#try:
   #resultado = 10 / 2
   #print('Ejecutando sin errores \n')
#except Exception as e:
   #print(f'Ha ocurrido un error. {e}')
#else:
      #print(resultado)  #

#try:

   #resultado = 20 / 5
   #print(resultado)
#except:
   #print('Ha ocurrido un error. {e}')
#else:
   #print(resultado)
#finally:
   #print('\nMe ejecuto siempre')

# try:
#       resultado = 16 * 5
#       print(resultado)
# except:
#    print('Hay un error. {e}')
# else:
#    print(resultado)
# finally:
#    print('Me voy a ejectur siempre')
